### ISSUE TITLE
Not make linux version, help please

### ISSUE THREAD

**Issue by yuriygorlov** [zcoinofficial/ccminer#9]
cuda_mtp/mtp.cu(54): warning: variable "diff" was declared but never referenced 
cuda_mtp/mtp.cu(55): warning: variable "TheNonce" was declared but never referenced 
cuda_mtp/mtp.cu(33): warning: variable "rwlock" was declared but never referenced 

1 error detected in the compilation of "/tmp/tmpxft_00005580_00000000-6_mtp.cpp1.ii". 
Makefile:2504: recipe for target 'cuda_mtp/mtp.o' failed 
make[2]: *** [cuda_mtp/mtp.o] Error 1 
make[2]: Leaving directory '/home/ferma/CCMINER/zcoin/ccminer' 
Makefile:2042: recipe for target 'all-recursive' failed 
make[1]: *** [all-recursive] Error 1 
make[1]: Leaving directory '/home/ferma/CCMINER/zcoin/ccminer' 
Makefile:616: recipe for target 'all' failed 
make: *** [all] Error 2

**Comment by yuriygorlov** [comment]
Fedora 25
Cuda 9.2 
-libstdc++

**Comment by djm34** [comment]
the origin of the error is missing

**Comment by j2h4u** [comment]
@djm34 it would be great to have linux binary in upcoming releases

**Comment by eLvErDe** [comment]
Hello,

Here is the actual error message:

```
/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9218): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9229): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9242): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9253): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9266): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9277): error: argument of type "const void *" is incompatible with parameter of type "const float *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9290): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9301): error: argument of type "const void *" is incompatible with parameter of type "const double *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9314): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9325): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9338): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9350): error: argument of type "const void *" is incompatible with parameter of type "const long long *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9363): error: argument of type "const void *" is incompatible with parameter of type "const int *"

/usr/lib/gcc/x86_64-linux-gnu/6/include/avx512fintrin.h(9374): error: argument of type "const void *" is incompatible with parameter of type "const int *"
```

It's coming from cuda_mtp/mtp.cu build and seems to be triggerred by a weird bug coming from GCC and/or CUDA toolkit.

Here you can find more information regarding the same bug (on Apache machine learning framework called MXNet, TensorFlow has similar issues):
https://github.com/apache/incubator-mxnet/issues/10558#issuecomment-384899345

Building this file without any -O{1,2,3} (yes even -O1 triggers the build issue) make the build work, "workaround" patch is coming.

**Comment by eLvErDe** [comment]
If you're interrested in you may want to use my docker image providing ccminer-mtp:

https://github.com/eLvErDe/docker-cuda-ccminer-mtp

If you're interrested in the binary only, you can browse:
http://packages.le-vert.net/mining/debian/
http://packages.le-vert.net/mining/ubuntu/

And grab ccminer-mtp*.deb from the proper pool-$distrib folder. It's a Debian package you can install directly and built for various Debian/Ubuntu version.
If you're interrested in the binary only, extract it from .deb file (it's an ar archive). There're build using CUDA 7.5 (Debian/Jessie), CUDA 8.0 (Debian/Stretch) and CUDA 9.1 (Debian/Buster; Ubuntu/Bionic...)
